# Weronika Jasiak
include("../Zadanie1/zad1.jl")
include("../Zadanie2/zad2.jl")
include("../Zadanie3/zad3.jl")

f1(x) = e^(1 - x) - 1
df1(x) = -e^(1 - x)

f2(x) = x * e^(-x)
df2(x) = -e^(-x) * (x - 1)

println("f1(x) = e^(1 - x) - 1")

println("\n[0.0, 2.0]")
(r, v, it, err) = mbisekcji(f1, 0.0, 2.0, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[0.1, 1.2]")
(r, v, it, err) = mbisekcji(f1, 0.1, 1.2, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[-0.1, 1.4]")
(r, v, it, err) = mbisekcji(f1, -0.1, 1.4, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[0.0, 150.0]")
(r, v, it, err) = mbisekcji(f1, 0.0, 150.0, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[-3.0, 3.0]")
(r, v, it, err) = mbisekcji(f1, -3.0, 3.0, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[0.5, 1.5]")
(r, v, it, err) = mbisekcji(f1, 0.5, 1.5, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\nf2(x) = x * e^(-x)")

println("\n[-1.0, 1.0]")
(r, v, it, err) = mbisekcji(f2, -1.0, 1.0, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[-0.4, 0.7]")
(r, v, it, err) = mbisekcji(f2, -0.4, 0.7, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)

println("\n[-0.5, 0.5]")
(r, v, it, err) = mbisekcji(f2, -0.5, 0.5, 10 ^ (-5.0), 10 ^ (-5.0))
println("Metoda bisekcji:")
println("r = ", r)
println("v = ", v)
println("it = ", it)
println("err = ", err)
